 databases:
    - name: myrailssite
      databaseName: Congolese_British_Grammar_School_Backend
      user: postgres
      ipAllowList: []

 services:
    - type: web
      name: myrailssite
      env: ruby
      buildCommand: "./bin/render-build.sh"
      startCommand: bundle exec rails s
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgresql
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
         generateValue: true
  - type: redis
    name: redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction
