databases:
  - name: postgres
    # ipAlloList: []
  
services:
  - type: web
    name: rails
    env: ruby
    buildCommand: "./bin/rend-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: RAILSLL_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase: 
          name: postgres
          property: connectionString

  # - type: redis
  #   name: redis
  #   ipAllowList: []
  #   plan: free
  #   maxmemoryPolicy: noeviction

